/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comics;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Mehdi Raza
 */
public class BookReader extends javax.swing.JFrame {

    private static final java.util.logging.Logger LOG = java.util.logging.Logger.getLogger(BookReader.class.getName());
    public static final String TOC_ENTRY_NAME="book.info";
    private Models.BookModel books;
    final int[] current=new int[1]; // current opened book id
    private Models.IndexModel indexModel;
    public static final String BOOKS_FOLDER=System.getProperty("user.dir") + "\\books\\";
    
    /**
     * Creates new form BookViewer
     */
    public BookReader() {
        initComponents();
    }

    public static void main(String args[]) {        
        try {
            /*javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++) {
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
            }*/
           UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookReader().setVisible(true);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectBookDialog = new javax.swing.JDialog();
        prevSelectBookButton = new javax.swing.JButton();
        nextSelectBookButton = new javax.swing.JButton();
        selectBookImage = new javax.swing.JLabel();
        toolbar = new javax.swing.JToolBar();
        openBookButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        firstButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        splitPane = new javax.swing.JSplitPane();
        indexPane = new javax.swing.JScrollPane();
        indexList = new javax.swing.JList<String>();
        indexList.setComponentOrientation(java.awt.ComponentOrientation.RIGHT_TO_LEFT);
        pagePane = new javax.swing.JScrollPane();
        page = new javax.swing.JLabel();

        selectBookDialog.setTitle("Select Book");
        selectBookDialog.setAlwaysOnTop(true);
        selectBookDialog.setLocation(new java.awt.Point(0, 0));
        selectBookDialog.setMinimumSize(new java.awt.Dimension(450, 265));
        selectBookDialog.setModal(true);
        selectBookDialog.setResizable(false);
        selectBookDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                selectBookDialogWindowOpened(evt);
            }
        });

        prevSelectBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comics/resources/prev.png"))); // NOI18N
        prevSelectBookButton.setMaximumSize(new java.awt.Dimension(30, 109));
        prevSelectBookButton.setMinimumSize(null);
        selectBookDialog.getContentPane().add(prevSelectBookButton, java.awt.BorderLayout.WEST);

        nextSelectBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comics/resources/next.png"))); // NOI18N
        nextSelectBookButton.setMaximumSize(new java.awt.Dimension(30, 109));
        nextSelectBookButton.setMinimumSize(null);
        selectBookDialog.getContentPane().add(nextSelectBookButton, java.awt.BorderLayout.EAST);

        selectBookImage.setToolTipText("Click to open Book");
        selectBookImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectBookImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectBookImageMouseClicked(evt);
            }
        });
        selectBookDialog.getContentPane().add(selectBookImage, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comic Books Reader");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        toolbar.setFloatable(false);
        toolbar.setRollover(true);

        openBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comics/resources/open_book.png"))); // NOI18N
        openBookButton.setToolTipText("Open Book");
        openBookButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        openBookButton.setEnabled(false);
        openBookButton.setFocusable(false);
        openBookButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openBookButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBookButtonActionPerformed(evt);
            }
        });
        toolbar.add(openBookButton);
        toolbar.add(jSeparator1);

        firstButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comics/resources/first_page.png"))); // NOI18N
        firstButton.setToolTipText("First Page");
        firstButton.setEnabled(false);
        firstButton.setFocusable(false);
        firstButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        firstButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });
        toolbar.add(firstButton);

        prevButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comics/resources/prev_page.png"))); // NOI18N
        prevButton.setToolTipText("Previous");
        prevButton.setEnabled(false);
        prevButton.setFocusable(false);
        prevButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        prevButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });
        toolbar.add(prevButton);

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comics/resources/next_page.png"))); // NOI18N
        nextButton.setToolTipText("Next");
        nextButton.setEnabled(false);
        nextButton.setFocusable(false);
        nextButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        toolbar.add(nextButton);

        lastButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comics/resources/last_page.png"))); // NOI18N
        lastButton.setToolTipText("Last Page");
        lastButton.setEnabled(false);
        lastButton.setFocusable(false);
        lastButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lastButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });
        toolbar.add(lastButton);
        toolbar.add(jSeparator2);

        getContentPane().add(toolbar, java.awt.BorderLayout.NORTH);

        indexPane.setPreferredSize(new java.awt.Dimension(150, 130));

        indexList.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        indexList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        indexList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        indexList.setMinimumSize(new java.awt.Dimension(100, 0));
        indexList.setNextFocusableComponent(pagePane);
        indexList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                indexListValueChanged(evt);
            }
        });
        indexPane.setViewportView(indexList);

        splitPane.setLeftComponent(indexPane);

        pagePane.setBackground(new java.awt.Color(255, 255, 255));

        page.setBackground(new java.awt.Color(255, 255, 255));
        pagePane.setViewportView(page);

        splitPane.setRightComponent(pagePane);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1050, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LOG.info("Loading books..");        
        try {
            books=new Models.BookModel(Loader.getInstance().loadBooks());
            openBookButton.setEnabled(true);
        } catch (NoBooksFoundException ex) {
            JOptionPane.showMessageDialog(this, "No Books found..");
            Logger.getLogger(BookReader.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened
    
    private void selectBookDialogWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_selectBookDialogWindowOpened
        LOG.info("selectBookDialogWindowOpened...");
        nextSelectBookButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                try {
                    selectBookImage.setIcon(new ImageIcon(books.nextBookImage(current).getScaledInstance(selectBookImage.getWidth(), -1, Image.SCALE_SMOOTH)));
                    selectBookDialog.setTitle(books.getTitle(current[0]));
                } catch (IOException ex) {
                    Logger.getLogger(BookReader.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        prevSelectBookButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                try {
                    selectBookImage.setIcon(new ImageIcon(books.prevBookImage(current).getScaledInstance(selectBookImage.getWidth(), -1, Image.SCALE_SMOOTH)));
                    selectBookDialog.setTitle(books.getTitle(current[0]));
                } catch (IOException ex) {
                    Logger.getLogger(BookReader.class.getName()).log(Level.SEVERE, null, ex);
                }
            }        
        });
        selectBookDialog.setLocationRelativeTo(this); // align center
        try {
            Image img=books.nextBookImage(current).getScaledInstance(selectBookImage.getWidth(), -1, Image.SCALE_SMOOTH);
            ImageIcon imgIcon=new ImageIcon(img);
            selectBookImage.setIcon(imgIcon);
            selectBookDialog.setTitle(books.getTitle(current[0]));
        } catch (IOException ex) {
            Logger.getLogger(BookReader.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_selectBookDialogWindowOpened

    private void selectBookImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectBookImageMouseClicked
        LOG.log(Level.INFO, "indexModel ...{0}", indexModel);
        try {
            indexModel=books.open(current[0]);
            if(!indexModel.getBook().isValid()) throw new InvalidBookException();
            indexModel.load();
            indexList.setModel(indexModel);
            selectBookDialog.setVisible(false);
            this.setTitle(indexModel.getBook().getBookName());
            
            indexList.setSelectedIndex(0);
            lastButton.setEnabled(true);
            nextButton.setEnabled(true);
        } catch (InvalidBookException ex) {
            JOptionPane.showMessageDialog(selectBookDialog, "The selected book archive \""+indexModel.getBook().getArchiveName()+"\" does not contain any \"book.info\" file for index information.");
            Logger.getLogger(BookReader.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_selectBookImageMouseClicked

    private void indexListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_indexListValueChanged
        if(evt.getValueIsAdjusting() || indexList.getSelectedIndex()==-1) return; // not interesting in adjusting events
        LOG.log(Level.FINEST, "Selected Index..{0}",indexList.getSelectedIndex());
        try {
            LOG.log(Level.FINEST, "selectIndex {0}", indexList.getSelectedIndex());
            page.setIcon(new ImageIcon(indexModel.getImage(indexList.getSelectedIndex()).getScaledInstance(pagePane.getWidth()-25, -1, Image.SCALE_SMOOTH)));
            pagePane.getVerticalScrollBar().setValue(0);
        } catch (IOException ex) {
            LOG.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_indexListValueChanged

    private void openBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBookButtonActionPerformed
        selectBookDialog.setVisible(true);
    }//GEN-LAST:event_openBookButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        indexList.setSelectedIndex(indexList.getSelectedIndex()+1);
        if(indexList.getSelectedIndex()==indexList.getModel().getSize()-1) {
            nextButton.setEnabled(false);
            lastButton.setEnabled(false);
            
        } 
        prevButton.setEnabled(true);
        firstButton.setEnabled(true);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        indexList.setSelectedIndex(indexList.getSelectedIndex()-1);
        if(indexList.getSelectedIndex()==0) {
            prevButton.setEnabled(false);
            firstButton.setEnabled(false);            
        }
        nextButton.setEnabled(true);
        lastButton.setEnabled(true);
    }//GEN-LAST:event_prevButtonActionPerformed

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        indexList.setSelectedIndex(0);
        prevButton.setEnabled(false);
        firstButton.setEnabled(false);
        lastButton.setEnabled(true);
        nextButton.setEnabled(true);
    }//GEN-LAST:event_firstButtonActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        indexList.setSelectedIndex(indexModel.getSize()-1);
        nextButton.setEnabled(false);
        lastButton.setEnabled(false);
        firstButton.setEnabled(true);
        prevButton.setEnabled(true);
    }//GEN-LAST:event_lastButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton firstButton;
    private javax.swing.JList<String> indexList;
    private javax.swing.JScrollPane indexPane;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JButton lastButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton nextSelectBookButton;
    private javax.swing.JButton openBookButton;
    private javax.swing.JLabel page;
    private javax.swing.JScrollPane pagePane;
    private javax.swing.JButton prevButton;
    private javax.swing.JButton prevSelectBookButton;
    private javax.swing.JDialog selectBookDialog;
    private javax.swing.JLabel selectBookImage;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
}
